<?php

/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="switcher-content">
    <div class="switcher-content__item amazon-logo">
        <img src="<?= $block->getViewFileUrl('images/amazon-logo-white.png'); ?>" />
    </div>
    <div class="switcher-content__item switcher-links">
        <a href="#" class="language">English</a>
        <a href="#" class="currency">USD - U.S. Dollar</a>
        <a href="#" class="country">United States</a>
    </div>
</div>
